version: '3.9'

services:
    app:
        container_name: emails-list-app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        ports:
            - 8000:80

    postgres:
        container_name: emails-list-postgres
        image: postgres:14.5
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - 5432:5432
