version: '3.9'

services:
    app:
        container_name: emails-list-app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mysql
        ports:
            - 8000:80

    mysql:
        container_name: emails-list-mysql
        image: mysql:8-debian
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        ports:
            - 5432:5432
